### ISSUE TITLE
1.4 Come up with a Project Introduction

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#10]
1. Task title ID: #10
2. What is the task about?

> Provide a brief introduction to your project, the intended purpose of the project, the impact of the project, and a brief overview 

3. What are the goals of the task?

> To allow all readers of our document to get a brief idea of our project, purpose and impact.

4. Success or completion criteria.

> To successfully provide an introduction of the project.

5. Allocated time

> 2 Days

6. Start date and end date of the issue/task

> 11/9 - 13/9

7. What is the priority of the task

> High priority

Issue/Task Comments Template 
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by Kai-i-i-i** [comment]
Reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
Provided a brief introduction of the project, the intended purpose, and a brief overview of what the reader will find in this section.

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by 2101309** [comment]
Reviewed

**Comment by KotoneZQ** [comment]
closed (23/9)
