### ISSUE TITLE
1.4.3 Intended Audience & Document Overview

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#11]
1. Task title ID: #11
2. What is the task about?

> To describe the different types of readers that the document is intended for, such as developers, project managers, marketing staff, users, testers, and documentation writers, describe what the rest of this document contains and how it is organized. Finally, to suggest a sequence for reading the document.

3. What are the goals of the task?

> To allow all readers to better understand the navigation of our document so they can browse with ease.

4. Success or completion criteria.

> To successfully provide a description of the intended audience and a document overview.

5. Allocated time

> 2 Days

6. Start date and end date of the issue/task

> 12/9 - 14/9

7. What is the priority of the task

> Medium priority

Issue/Task Comments Template 
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by Kai-i-i-i** [comment]
Added a description of the intended audience, a document overview and a suggested reading sequence for each type of reader. Pending review from other team members.

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
Closed - 22-9
