### ISSUE TITLE
1.4.4 References & Acknowledgments

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#12]
1. Task title ID: #12
2. Include reference links to resources found online.
3. To credit the authors of the research material we use.
4. Successfully include links under the references section in our M1 report.
5. 2 days.
6. 12/09/23 - 14/09/23.

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
Added some references about background literature. 11/09/23 - 13/09/23.

**Comment by brandonbljl** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by 2101309** [comment]
Reviewed
