### ISSUE TITLE
1.5.1 Write an overview of the Product

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#13]
1. Task title ID: #13
2. What is the task about? Please describe in detail.

    The task includes offering a comprehensive overview of the product perspective, with an emphasis on how our product interacts with its environment and usage context. This includes describing the main components, their interactions, and the external factors that affect the functionality of the product. In addition, a diagram of the system's architecture at a high level will be created to visually represent these interactions for improved comprehension.

3. What are the goals of the task? Please describe in detail.

    This task's primary objectives are to improve the clarity and comprehension of our product's perspective. Specifically, we strive to clarify the functional and contextual relationships between our product and its environment. By creating a system architecture diagram at a high level, we hope to provide stakeholders with a visual overview of the product's fundamental components and their interconnections.

4. Success or completion criteria. Please describe in detail.

    A detailed and well-written product perspective description that effectively explains the product's interactions and context.
    The development of a high-level system architecture diagram that depicts the product's interactions with its environment.
    The description and diagram are accessible to both technical and non-technical stakeholders.
    

5. Allocated time

    2 days

6. Start date and end date of the issue/task

    The task officially begins on September 11, 2023, and concludes on September 13, 2023.
    
Issue/Task Comments Template 
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by 2101309** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by brandonbljl** [comment]
1. Describe the work done in detail.

    Provided an in-depth overview of the web-based workload management system

2. Has this work been committed to the repo?

    Yes, the product description and system diagram have been added to the repository for review and collaboration.

3. How does the work affect success or completion criteria?

    By providing a distinct product perspective, a high-level system architecture diagram, and accessibility for both technical and non-technical stakeholders, the work meets the completion criteria.

4. Start date and end date of the work done

    The assignment began on September 11, 2023, and was accomplished on September 13, 2023.

**Comment by Kai-i-i-i** [comment]
Added a overview, context and origin as well as the relation to the larger system.

**Comment by brandonbljl** [comment]
Closed - 22/9
