### ISSUE TITLE
1.5.2 List out the Product Functionality

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#14]
1. Task title ID: #14
2. What is the task about? Please describe in detail.
Summarize the major functions the product must perform or must let the user perform. Write a high-level summary in this section, and elaborate in the section below. These can be at the level given in the project description. Use Activity diagrams to capture the business flow and processes in this section for the various product functionality.
3. What are the goals of the task? Please describe in detail.
To clearly lay out the different requirements that we will be following to construct our system, and the functions that it will be able to perform.
4. Success or completion criteria. Please describe in detail.
Completely detail all possible functions that the system will have, and go in-depth into each function and what will happen when users interact with it.
5. Allocated time
3 days
6. Start date and end date of the issue/task
11/9/2023 to 14/9/2023
Issue/Task Comments Template 
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by 2101309** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by gitdanzel** [comment]
Issue/Task Comments Template 
1. Describe the work done in detail. 
Sorted out and wrote all product functionalities into a function per line, and gave a brief, high-level summary of each function
2. Has this work been committed to the repo?
Yes
3. How does the work affect success or completion criteria?
It adheres very strictly to the success and completion criteria
6. Start date and end date of the work done 
11/9/2023 to 18/9/2023

**Comment by KotoneZQ** [comment]
added the activity diagram

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed activity diagram

**Comment by gitdanzel** [comment]
Closed on 26/09/2023
