### ISSUE TITLE
1.5.3 List out the Assumptions & Dependencies

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#15]
1. Task title ID: #15
2. What is the task about?

> To list any assumed factors that could affect the requirements stated in the document. The project could be affected if these assumptions are incorrect, are not shared, or change. Also to identify any dependencies the project has on external factors, such as software components that we intend to reuse from another project.

3. What are the goals of the task?

> To list out our assumptions just in case of any unforeseen situations.

4. Success or completion criteria

> To successfully list any assumed factors that could affect the requirements stated in the document.

5. Allocated time

> 2 Days

6. Start date and end date of the issue/task

> 12/9 - 14/9

7. What is the priority of the task

> Medium priority

Issue/Task Comments Template
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by Kai-i-i-i** [comment]
Added 5 assumptions and 5 dependencies to the document, Pending review from other team members.

**Comment by KotoneZQ** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
Closed - 22-9
