### ISSUE TITLE
1.6.4.1 List out the Performance Requirements

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#16]
1. Task title ID: #16
2. What is the task about?
To discern and write out the requirements that the system should be able to perform, specifically requirements that have to do with the performance of the system.
3. What are the goals of the task? Please describe in detail.
To clearly lay out the different requirements that we will be trying to achieve while building our system. Specifically, these requirements will pertain to system performance.
4. Success or completion criteria. Please describe in detail.
Write insightful, in-depth descriptions of the performance functionalities that our system will have in the final product.
5. Allocated time
3 days
6. Start date and end date of the issue/task
16/9/2023 to 19/9/2023
7. What is the priority of this task?
High

Issue/Task Comments Template

Describe the work done in detail.
Has this work been committed to the repo?
How does the work affect success or completion criteria?
Start date and end date of the work done

**Comment by KotoneZQ** [comment]
reviewed

**Comment by 2101309** [comment]
added a new requirement reviewed needed. 
regarding portability if we want it on other devices

**Comment by 2101309** [comment]
reviewed

**Comment by 2101309** [comment]
added portability part which allows mobile and tablet to use the system. need review

**Comment by Jr-Goh** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by gitdanzel** [comment]
reveiwed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by 2101309** [comment]
reviewed.

**Comment by gitdanzel** [comment]
Closed on 26/09/2023
