### ISSUE TITLE
1.6.4.2 List out the Safety & Security Requirements

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#17]
1. Task title ID: #17
2. What is the task about?

> To specify requirements that are concerned with possible loss, damage, or harm that could result from the use of the product. Define any safeguards or actions that must be taken, as well as actions that must be prevented and specify any requirements regarding security or privacy issues surrounding use of the product or protection of the data used or created by the product.

3. What are the goals of the task?

> To list out the respective safety and security requirements.

4. Success or completion criteria.

> To successfully specify all requirements that should be protected, how we plan to protect them and any policies that we need to follow.

5. Allocated time

> 3 Days

6. Start date and end date of the issue/task

> 16/9 - 19/9

7. What is the priority of the task

> Medium priority

Issue/Task Comments Template
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by Kai-i-i-i** [comment]
Added requirements such as data encryption, multi factor authentication, policies such as GDPR and HIPAA as well as user identity authentication. Pending review from other team members.

**Comment by 2101309** [comment]
added other additional security requirements.

pending review from other team members.

**Comment by brandonbljl** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
Closed 22-9
