### ISSUE TITLE
1.6.5 List out any Other Requirements

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#18]
1. Task title ID: #18
2. What is the task about? Please describe in detail.
To detail the standards and protocols that our system will adhere to.
3. What are the goals of the task? Please describe in detail.
Our system will need to adhere to the industry standards and protocols to safeguard user data, maintain trust, and avoid legal consequences by regularly undergoing audits and assessments6. Success or completion criteria. Please describe in detail.
4. Allocated time
1 day
5. Start date and end date of the issue/task
18/9/2023 to 19/9/2023
6. What is the priority of the task
Medium

Issue/Task Comments Template . 
1. Describe the work done in detail.
Conducted research on the various protocols and standards that web systems have to adhere to so that no legal issues should arise. Wrote out the standards and protocols.
2. Has this work been committed to the repo?
Yes
3. How does the work affect success or completion criteria?
It adheres to the success and completion criteria.
4. Start date and end date of the work done 
18/9/2023 to 19/9/2023

**Comment by Kai-i-i-i** [comment]
Moved compliance requirements to this section.

**Comment by 2101309** [comment]
Reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by gitdanzel** [comment]
Closed on 26/09/2023
