### ISSUE TITLE
1.7.1 Calculate the Software Estimation

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#19]
1. Task title ID: #19
2. What is the task about? Please describe in detail.
using the UCP method to estimate the project size, cost and duration,  we have also justified the score given. 
3. What are the goals of the task? Please describe in detail.
This is to understand the estimated size, cost and duration of our project
4. Success or completion criteria. Please describe in detail.
Calculate the correct results using the correct formula to properly estimate the project size, cost and duration.
5. Allocated time
2 day
6. Start date and end date of the issue/task
18sept - 20sept
7. What is the priority of the task
> High priority

Issue/Task Comments Template 
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by 2101309** [comment]
Will verify again on the use case description and start calculating the transaction of each scenario.

**Comment by 2101309** [comment]
done verifying the use case description and each of the transaction
ongoing calculating using the UCP method.

**Comment by KotoneZQ** [comment]
18 Sept 2023 2..45pm - 6.10 pm

Estimate the project size, cost and time duration
> Count the number of transactions in each use case
> Calculate the TTCP, EF, and TCF for UCP
> Calculate the effort estimation for cost and time

**Comment by Jr-Goh** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by 2101309** [comment]
22/9

closed
