### ISSUE TITLE
1.1 Schedule meeting with client

### ISSUE THREAD

**Issue by Kai-i-i-i** [KotoneZQ/INF2001_P7-6_Project#2]
1. Task title ID: #02
2. What is the task about?

> Schedule a meeting with the client for a QA session

3. What are the goals of the task?

> To discuss with the client on the project requirement as provided for clarification

4. Success or completion criteria

> To schedule a timeslot with the client

5. Allocated time

> 4 Days (2 Schedule meeting total)

6. Start date and end date of the issue/task

> 29 Aug 2023 - 3 Sept 2023

7. What is the priority of the task

> High priority

Issue/Task Comments Template
1. Describe the work done in detail. Check the number of available timeslots in the Google Spreadsheets provided by our professor
- Discuss together which timeslot is suitable for us to schedule by checking each member's availability.
- Indicate our group number on the chosen timeslot for registration.
2. Has this work been committed to the repo? Yes
3. How does the work affect success or completion criteria?
- Upon success, we can ask questions about our project so that we can have a clear and better understanding on how to proceed.
4. Start date and end date of the work done: 29 Sep 2023 - 31 Sep 2023

**Comment by Kai-i-i-i** [comment]
everyone decided on the meeting time

**Comment by KotoneZQ** [comment]
reviewed and scheduled time

**Comment by Jr-Goh** [comment]
Reviewed meeting time

**Comment by brandonbljl** [comment]
Reviewed timing

**Comment by KotoneZQ** [comment]
Scheduled another timing as backup
Timeslot: 3pm, 11 Sept (Mon)

**Comment by KotoneZQ** [comment]
Reviewed and done

**Comment by KotoneZQ** [comment]
Closed as Completed (11/9)
