### ISSUE TITLE
1.8 Create Use Case Descriptions

### ISSUE THREAD

**Issue by Kai-i-i-i** [KotoneZQ/INF2001_P7-6_Project#20]
1. Task title ID: #20
2. What is the task about?

> Provide a brief description of each use case that we come up with based on the requirements provided.

3. What are the goals of the task?

> To complete the description of all the use case with relevant information of the actor, conditions and scenarios

4. Success or completion criteria

> Complete write-up of all of the use case

> Complete the Use Case Model (#04)

5. Allocated time

> 2 days

9. Start date and end date of the issue/task

> 19 Sept - 21 Sept

7. What is the priority of the task

> High priority

Issue/Task Comments Template
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by KotoneZQ** [comment]
17 Sept 2023 8pm - 12am

Create a use case diagram/model
Come up with use case descriptions based on the model

Follow up with #4

**Comment by KotoneZQ** [comment]
18 Sept 2023 2..45pm - 6.10 pm
Modify the use case descriptions

> Update alternative scenarios

**Comment by Jr-Goh** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by KotoneZQ** [comment]
closed (22/9)
