### ISSUE TITLE
1.9 Define the terms used in the M1 report

### ISSUE THREAD

**Issue by Kai-i-i-i** [KotoneZQ/INF2001_P7-6_Project#21]
1. Task title ID: #21
2. What is the task about?
> To describe the terms that are used in the project report
3. What are the goals of the task?
> To provide a brief description of the term such as the definition for non-developer to understand easily
4. Success or completion criteria.
> The report writing
5. Allocated time
> 2 Days
6. Start date and end date of the issue/task
> 21 Sept 2023- 23 Sept 2023
7. What is the priority of the task
> Low priority

Issue/Task Comments Template 
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by KotoneZQ** [comment]
added the terms that are used in the report
- provide definition of these terms

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed!

**Comment by 2101309** [comment]
added a few more terms to the dictionary.

**Comment by KotoneZQ** [comment]
reviewed

**Comment by KotoneZQ** [comment]
closed (22/9)
