### ISSUE TITLE
1.5 Overall Description

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#22]
1. Task title ID: #22
2. What is the task about?

> Describe the different types of reader that the document is intended for, such as developers, project managers, marketing staff, users, testers, and documentation writers (In your case it would probably be the “client” and the professor). Describe what the rest of this document contains and how it is organized. Suggest a sequence for reading the document, beginning with the overview sections and proceeding through the sections that are most pertinent to each reader type.

> This sections includes the Product Overview(1.2.1), Product Functionality(1.2.2), Assumptions and Dependencies(1.2.3). Also Included the system architecture diagram into the report. 11/09/23 - 14/09/23.

3. What are the goals of the task?

> To provide readers an understanding of our topic and what are we trying to do.

4. Success or completion criteria.

> To successfully educate readers what is the purpose of this report.

5. Allocated time

> 4 Days

16. Start date and end date of the issue/task

> 11/9 - 14/9

7. What is the priority of the task

> High priority

**Comment by Kai-i-i-i** [comment]
Added a overview, context and origin as well as the relation to the larger system, pending review from teammates

**Comment by Jr-Goh** [comment]
Reviewed. This sections includes the Product Overview(1.2.1), Product Functionality(1.2.2), Assumptions and Dependencies(1.2.3). Also Included the system architecture diagram into the report. 11/09/23 - 14/09/23.

**Comment by brandonbljl** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by 2101309** [comment]
reviewed
