### ISSUE TITLE
1.6 Specific Requirements

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#23]
1. Task title ID: #23
2. What is the task about? Please describe in detail.

    The task requires identifying the intended audience and organising a document, as well as describing its content and structure. It also includes recommending a reading order for the document, beginning with the overview sections and then moving on to the sections that are most important to various reader types.

3. What are the goals of the task? Please describe in detail.

    - Clearly identify and describe the various categories of document readers.
    - Specify the document's content and organisation, including the contents of each section.
    - Provide a reading order that addresses the demands and interests of each reader type.

4. Success or completion criteria. Please describe in detail.

    - A thorough description of the various reader categories, including developers, project managers, marketing personnel, users, testers, and documentation writers.
    - A concise summary of the document's structure and content, highlighting the sections and their functions.
    - A well-structured reading sequence, commencing with the overview sections and proceeding to sections most pertinent to each reader type.

5. Allocated time

    1 Week

6. Start date and end date of the issue/task

    13 September 2023 to 19 September 2023

7. What is the priority of the task?

    Medium Priority

Issue/Task Comments Template 
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by 2101309** [comment]
reviewed

**Comment by brandonbljl** [comment]
1. Describe the work done in detail.

    Work includes sections 3.1 (User Interface Requirements), 3.2 (Functional Requirements), 3.3 (Use Case Diagram), and 3.4 (Non-Functional Requirements), with an emphasis on defining requirements, developing the user interface, and producing visual representations of system interactions.
    
    I actively participated in the design of the website's User Interface (UI), providing valuable input and suggestions to guarantee an effective and user-friendly interface.

2. Has this work been committed to the repo?


    Yes, the work associated with these sections, including the UI recommendations and requirement descriptions, has been committed to the repository for review and discussion.


3. How does the work affect success or completion criteria?


    The work contributes to the task's success and completion criteria by:

    - Contributing to the definition and specification of the document's content and organisation, particularly in the sections pertaining to requirements.

    - Ensuring that specific sections, such as user interface, functional, non-functional, and other requirements, are appropriately addressed and documented.

    - Indirectly, the work supports the development of a well-structured reading sequence, as readers can follow the document from its overview sections to its detailed sections, which is consistent with the objectives of the task.

4. Start date and end date of the work done

    The work on these particular sections of the document commenced on September 13, 2023, and was concluded on September 19, 2023.

**Comment by brandonbljl** [comment]
closed - 22/9
