### ISSUE TITLE
1.7 Project Estimation & Plan

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#24]
1. Task title ID: #24
2. What is the task about? 
> To estimate the duration, cost, and size of the project and provide a project plan
3. What are the goals of the task?
> To estimate the duration, cost, and size of the project using Use Case Points
> To plan out the project management using the Gantt Chart
4. Success or completion criteria. Please describe in detail.
> Calculate the duration, cost and size of the project (#19)
> Complete the Gantt Chart (#7)
5. Allocated time
> 2 Days
6. Start date and end date of the issue/task
> 18 Sept - 20 Sept 2023
7. What is the priority of the task
> High priority

Issue/Task Comments Template 
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by Kai-i-i-i** [comment]
Discussed the and set the estimated effort required to complete the project with teammates

**Comment by 2101309** [comment]
22/9
agreed on the discussion

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed
