### ISSUE TITLE
2.1.1 Create a Class Diagram Design

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#27]
1. Task title ID: #27

2. What is the task about?

> To create a class diagram of the project using the OOP concept.

3. What are the goals of the task?

> To be able to make a software design of the project using OOP concept in an ECB diagram

4. Success or completion criteria.

> Able to identify entities, control, boundary & interface classes used in the project

> Able to understand the class diagram

5. Allocated time

>  2 Days

6. Start date and end date of the issue/task

> 11 Oct 2023 - 13 Oct 2023

7. What is the priority of the task

> High Priority

**Comment by KotoneZQ** [comment]
9 Oct 2023

Create Class Diagram

> Identity the entities, control and boundary class

> Indicate the relationship between entities

> Think about the methods and attribute of class

**Comment by KotoneZQ** [comment]
21 Oct 2023

Modify the Class Diagram

> Add interface into the ECB Diagram

> Modify and add methods

**Comment by 2101309** [comment]
discussed and reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
discussed and reviewed

**Comment by KotoneZQ** [comment]
Update  the class diagram and reviewed

**Comment by Jr-Goh** [comment]
Discussed and reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by 2101309** [comment]
closed 28/10
