### ISSUE TITLE
2.1.2 Create a Sequence Diagram Design

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#28]
1. Task title ID: #28

2. What is the task about?
> To create a sequence diagram based on our project use case description to describe the interaction between system and user

3. What are the goals of the task?

> To be able to have an understanding and readable process of the interaction

4. Success or completion criteria.

> Complete Class Diagram (#27)

> Use Case Description (#20)

> Provide an understandable sequence diagram

5. Allocated time

>  2 Days

6. Start date and end date of the issue/task

> 9 Oct 2023 - 11 Oct 2023

7. What is the priority of the task

> High Priority

**Comment by KotoneZQ** [comment]
9 Oct 2023

Create a sequence diagram of Manager user

> Draw out the process of the Allocate job use case

**Comment by KotoneZQ** [comment]
21 Oct 2023

Create a sequence diagram of Staff user

> Draw out the process of the View Weekly job Assignment use case

Modify the sequence diagram

> Add interface class into the diagram

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
discussed and reviewed

**Comment by KotoneZQ** [comment]
update the sequence diagram for managers and reviewed

**Comment by Jr-Goh** [comment]
Discussed and reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by 2101309** [comment]
reviewed

**Comment by KotoneZQ** [comment]
closed (28/10)
