### ISSUE TITLE
2.3 Made Changes in Use Case Diagram

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#29]
1. Task title ID: #29
2. What is the task about?

> Made changes to the use case diagram

3. What are the goals of the task?

> Modify the Use Case Diagram based on the M1 feedback given for better improvement

4. Success or completion criteria.

> Complete Use Case Model (#30)

> Complete Use Case Description (#36)

5. Allocated time

> 4 Days

6. Start date and end date of the issue/task

> 21 Oct 2023 - 25 Oct 2023

7. What is the priority of the task

> High Priority

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed and discussed

**Comment by 2101309** [comment]
reviewed

**Comment by 2101309** [comment]
reviewed and closed on 28/10
