### ISSUE TITLE
1.2 Discuss & Decide on questions to ask the client.

### ISSUE THREAD

**Issue by Kai-i-i-i** [KotoneZQ/INF2001_P7-6_Project#3]
1. Task title ID: #03
2. This task is about deciding/finalizing questions that the team wants to ask the client during the first meeting.
3. The goal is to clarify any doubts about, 1. the initial requirements 2. unexpected situations, success measurement and flow of using the new system.
4. Will be considered successful if all members' doubts are clarified and are able to proceed to in other tasks after this
5. 1 week
6. 29 Aug - 5 Sep
7. High priority

Issue/Task Comments Template 
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done (6 Sep - 6 Sep)

**Comment by gitdanzel** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
Reviewed and closed (11/9)
