### ISSUE TITLE
2.3.1 Modify the Use Case Model

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#30]
1. Task title ID: #30
2. What is the task about?

> Make changes to the Use Case Model based on the M1 feedback given for better improvement

3. What are the goals of the task?

> Modify the Use Case model based on the feedback

4. Success or completion criteria.

> Complete the changes made in the use case model

5. Allocated time

> 2 Days

6. Start date and end date of the issue/task

> 21 Oct 2023 - 23 Oct 2023

7. What is the priority of the task
> High Priority

**Comment by 2101309** [comment]
added external database entity to the diagram
and modified the task to purpose.
review needed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed and discussed

**Comment by 2101309** [comment]
closed 28/10
