### ISSUE TITLE
2.2 Made Changes in Requirement

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#32]
1. Task title ID: #32
2. What is the task about? Please describe in detail.

> Made changes to the requirement according to the M1 given feedback, further improving the product.

3. What are the goals of the task?

> Apply changes made in all the requirements to meet what is mentioned in the M1 feedback.

4. Success or completion criteria.

> Complete User Interface Requirements (#38)

> Complete Functional Requirements (#39)

> Complete Non-Functional Requirements (#40)

> Complete Remove unnecessary Requirements (#41)

5. Allocated time

> 3 Days

6. Start date and end date of the issue/task

> 16 Oct 2023 - 19 Oct 2023

7. What is the priority of the task

> High Priority

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
discussed and reviewed

**Comment by Jr-Goh** [comment]
Discussed and reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by gitdanzel** [comment]
Issue/Task Comments Template

Describe the work done in detail.
Revised and improved on the functional and non-functional requirements based on the 7 traits of good requirements.
Has this work been committed to the repo?
Yes
How does the work affect success or completion criteria?
It adheres very strictly to the success and completion criteria
Start date and end date of the work done
16/10/2023 to 19/10/2023
