### ISSUE TITLE
2.1  Create Software Design

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#33]
1. Task title ID: #33
2. What is the task about? Please describe in detail.

> Create a software design regarding of our project

3. What are the goals of the task? Please describe in detail.

> Create three types (ECB, Sequence & Component) of diagram to describe and show how our proposed solution software works

4. Success or completion criteria. Please describe in detail.

> Complete Class Diagram (#27)

> Complete Sequence Diagram (#28)

> Complete Component Diagram (#34)

5. Allocated time

> 5 Days

6. Start date and end date of the issue/task

> 9 Oct - 14 Oct 2023

7. What is the priority of the task

> High Priority

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
discussed with team to make the diagrams and reviewed

**Comment by Jr-Goh** [comment]
Discussed and reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by 2101309** [comment]
discussed and reviewed

**Comment by KotoneZQ** [comment]
closed (29/10)
