### ISSUE TITLE
2.1.3 Create a Component diagram Design

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#34]
1. Task title ID: #34
2. What is the task about? Please describe in detail.

> Create a component diagram based on our project to show how the functionality of the system

3. What are the goals of the task? Please describe in detail.

> Create a component diagram to show how the proposed solution functions as a system with the required component

4. Success or completion criteria. Please describe in detail.

> Complete Class Diagram (#27)

5. Allocated time

> 2 Days

6. Start date and end date of the issue/task

> 12 Oct 2023 - 14 Oct 2023

7. What is the priority of the task

> High Priority

**Comment by KotoneZQ** [comment]
21 Oct 2023

Create a component diagram

> Group various classes into common components

> Create and link components using relationship

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
discussed and reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
Discussed and reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by 2101309** [comment]
discussed and reviewed
