### ISSUE TITLE
2.4 Update the Project Management Plan

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#35]
1. Task title ID: #35
2. What is the task about?

> Update the project management plan based on the M1 Feedback given

3. What are the goals of the task?

> Modify the Gantt Chart tasks to meet what is stated in the feedback

> Create tasks for M2

4. Success or completion criteria.

> Modify the changes made in the Gantt Chart

> Assign tasks and estimate duration for each member (M2)

5. Allocated time

> 2 Days

6. Start date and end date of the issue/task

> 25 Oct 2023 - 27 Oct 2023

7. What is the priority of the task

> High Priority

**Comment by KotoneZQ** [comment]
21 Oct 2023

Update the Gantt Chart

> Create new tasks for M2

> Modify the task name for M1 based on the feedback

> Estimate the duration for each M2 tasks required

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed and discussed

**Comment by 2101309** [comment]
reviewed

**Comment by KotoneZQ** [comment]
closed (28/10)
