### ISSUE TITLE
2.3.2 Modify the Use Case Description

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#36]
1. Task title ID: #36
2. What is the task about?

> Make changes to the Use Case Description based on the Use Case Model and M1 feedback for better improvement

3. What are the goals of the task?

> Modify all the changes that is required in the Use Case Description based on the modified Use Case Model

4. Success or completion criteria.

> Complete the changes made in the Use Case Description

5. Allocated time

> 2 Days

6. Start date and end date of the issue/task

> 23 Oct 2023 - 25 Oct 2023

7. What is the priority of the task

> High Priority

**Comment by 2101309** [comment]
added the database as an actor and modified the scenarios with the database. needed review

**Comment by Jr-Goh** [comment]
Edited the affected use case to include usage of Database. Reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed and discussed
