### ISSUE TITLE
2.5 Define the terms used in the M2 report

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#37]
1. Task title ID: #37
2. What is the task about?

> Define the terms and explanations that are used in the report

3. What are the goals of the task?

> Write an explanation for the terms and diagram, so that reader are able to understand easily

4. Success or completion criteria.

> Complete write-up of the definition and explanation

5. Allocated time

> 2 Days

6. Start date and end date of the issue/task

> 26 Oct 2023 - 28 Oct 2023

7. What is the priority of the task

> Medium Priority

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by brandonbljl** [comment]
Describe the work done in detail.
- The work involved adding a detailed description for the sequence diagram in the "View Weekly Job Assignments" section of the M2 report

Has this work been committed to the repo?
- Yes

How does the work affect success or completion criteria?
- The M2 report is enhanced in quality, as it now includes a detailed description for the sequence diagram.

**Comment by KotoneZQ** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed and discussed

**Comment by 2101309** [comment]
reviewed

**Comment by brandonbljl** [comment]
closed - 29/10
