### ISSUE TITLE
2.2.1 Modify the User Interface Requirements

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#38]
1. Task title ID: #38
2. What is the task about?

> The task involves revising the User Interface Requirements of the project with a focus on User Interface Branding, Accessibility and Usability, and UI Layout and Elements.

3. What are the goals of the task?

> Modify the requirements based on the feedback we got from M1

4. Success or completion criteria.

> The revised User Interface Requirements should align with the feedback received from M1, addressing all mentioned concerns, improvements, and suggestions.

5. Allocated time

> 2 Days

6. Start date and end date of the issue/task

> 16 Oct 2023 - 18 Oct 2023

7. What is the priority of the task

> High Priority

**Comment by brandonbljl** [comment]
1. Describe the work done in detail.

	The work involved revising the User Interface (UI) requirements based on the feedback received during Milestone 1 (M1).

2. Has this work been committed to the repo?

	Yes, the revised UI requirements have been committed to the repository

3. How does the work affect success or completion criteria?

	The successful completion of this task is contingent on ensuring that the revised UI requirements accurately address the feedback from M1.

**Comment by Kai-i-i-i** [comment]
discussed and reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
Discussed and reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by 2101309** [comment]
reviewed

**Comment by brandonbljl** [comment]
closed - 29/10
