### ISSUE TITLE
2.2.2 Modify the Functional Requirement

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#39]
1. Task title ID: #39
2. What is the task about?

> Made changes in the Functional Requirement based on the given M1 feedback for better improvement

3. What are the goals of the task?

> Modify what is needed to be made in the functional requirement, meet the 7 traits as mentioned in the feedback

4. Success or completion criteria.

> All requirements meet the 7 traits of good requirements.

5. Allocated time

> 3 Days

6. Start date and end date of the issue/task

> 16 Oct 2023 - 19 Oct 2023

7. What is the priority of the task

> High Priority

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by gitdanzel** [comment]
Issue/Task Comments Template

Describe the work done in detail.
Revised and improved on the functional requirements based on the 7 traits of good requirements.
Has this work been committed to the repo?
Yes
How does the work affect success or completion criteria?
It adheres very strictly to the success and completion criteria
Start date and end date of the work done
16/10/2023 to 19/10/2023
