### ISSUE TITLE
1.6.3 Create a Use Case Model

### ISSUE THREAD

**Issue by Kai-i-i-i** [KotoneZQ/INF2001_P7-6_Project#4]
Follow the template in the slides (read ahead week 3 lecture materials).

1. Task title ID: #04
2. What is the task about?
Complete use-case diagram on the system and every member of the team to write a detailed use-case description.
3. What are the goals of the task? Please describe in detail.
Create the use case diagram based on the functional requirement.
4. Success or completion criteria. Please describe in detail.
The use case diagram can explain what each actor can do.
5. Allocated time
3 days
6. Start date and end date of the issue/task
9/14 - 9/17
8. What is the Priority of the task?
High priority

Issue/Task Comments Template 
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by KotoneZQ** [comment]
17 Sept 2023 8pm - 12am

- Create a use case diagram/model
- Come up with use case descriptions based on the model

**Comment by 2101309** [comment]
please do a verification again on the use case diagram

**Comment by Kai-i-i-i** [comment]
Reviewed and vetted the model and descriptions

**Comment by KotoneZQ** [comment]
reviewed

**Comment by KotoneZQ** [comment]
18 Sept 2023 2..45pm - 6.10 pm
Modify the use case descriptions

> Update alternative scenarios

**Comment by brandonbljl** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by 2101309** [comment]
reviewed the use case description and it transcation

**Comment by KotoneZQ** [comment]
reviewed

**Comment by 2101309** [comment]
23/9
Closed.
