### ISSUE TITLE
2.2.3 Modify the Non-Functional Requirements

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#40]
1. Task title ID: #40
2. What is the task about?

> To review and update the non functional requirements, if possible.

3. What are the goals of the task?

> To make sure the non functional requirements are better crafted and more updated of any changes to the scope are made.

4. Success or completion criteria.

> When it is successfully reviewed.

5. Allocated time

> 3 Days

6. Start date and end date of the issue/task

> 16 Oct 2023 - 19 Oct 2023

7. What is the priority of the task

> Medium

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed and discussed

**Comment by 2101309** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
Closed 28/10
