### ISSUE TITLE
2.2.4 Remove unnecessary Requirements

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#41]
1. Task title ID: #41
2. What is the task about?

> To remove the extra, unnecessary requirements.

3. What are the goals of the task?

> To remove the extra, unnecessary requirements if any, as there may be some extra assumptions we added on M1.

4. Success or completion criteria.

> To successfully review the requirements.

5. Allocated time

> 2 Days

6. Start date and end date of the issue/task

> 17 Oct 2023 - 19 Oct 2023

7. What is the priority of the task

> Medium

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed and discussed

**Comment by 2101309** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
Closed 28/10
