### ISSUE TITLE
3.1 Architecture Design

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#42]
1. Task title ID: #42
2. What is the task about? Please describe in detail. - Describe which architecture design pattern is suitable for our project and why.
3. What are the goals of the task? Please describe in detail. - To successfully justify why we picked the architecture design pattern.
4. Success or completion criteria. Please describe in detail. - Successfully added reasons why, with diagrams to justify our selections.
5. Allocated time - 2 Days
6. Start date and end date of the issue/task - 18/11 - 20/11
7. What is the priority of the task - Medium

**Comment by Kai-i-i-i** [comment]
Added reasons/descriptions as to why we chose MVC, along with a diagram - 18/11

**Comment by KotoneZQ** [comment]
reviewed (25/11)

**Comment by 2101309** [comment]
reviewed

**Comment by Jr-Goh** [comment]
Reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
Closed - 26/11
