### ISSUE TITLE
3.1.1 Create a Software Architecture Design Diagram

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#43]
1. Task title ID: #43
2. What is the task about? Please describe in detail. - To create a architecture diagram to justify the architecture pattern we chosen.
3. What are the goals of the task? Please describe in detail. - To successfully illustrate our architecture design.
4. Success or completion criteria. Please describe in detail. - Successfully created an image to support our decision of picking certain architecture design pattern.
5. Allocated time  - 2 Days
6. Start date and end date of the issue/task - 18/11 - 20/11
7. What is the priority of the task - Medium

**Comment by Kai-i-i-i** [comment]
Created a diagram to show how MVC is suitable for our project - 18/11

**Comment by KotoneZQ** [comment]
reviewed (25/11)

**Comment by 2101309** [comment]
reviewed

**Comment by Jr-Goh** [comment]
Reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
Closed - 26/11
