### ISSUE TITLE
3.1.2 Design Pattern

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#44]
1. Task title ID: #44
2. What is the task about? Write about and justify the design patterns we will be utilising for our project
3. What are the goals of the task? - Choosing and justifying the design patterns we will use
4. Success or completion criteria. - Choosing appropriate design patterns that fit our web system
5. Allocated time - 2 days
6. Start date and end date of the issue/task - 18/11/23 to 20/11/23
7. What is the priority of the task -  High

**Comment by KotoneZQ** [comment]
24 Nov 2023

Make changes to the detailed pattern (factory & command)

**Comment by 2101309** [comment]
reviewed

**Comment by Jr-Goh** [comment]
Reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by gitdanzel** [comment]
Issue/Task Comments Template 
1. Describe the work done in detail. - Conducted research on the various design patterns, and settled on two that we felt were appropriate to our web system.
2. Has this work been committed to the repo? - Yes
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done  - 18/11/23 to 20/11/23

**Comment by brandonbljl** [comment]
reviewed
