### ISSUE TITLE
3.2 Design a Prototype Wireframe

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#45]
1. Task title ID: #45
2. What is the task about? Please describe in detail.

    The task involves creating a wireframe prototype based on the specific requirements provided by the client.

3. What are the goals of the task? Please describe in detail.

    The primary goals of the task are to understand client requirements, create an intuitive user flow, incorporate client branding, gather stakeholder feedback, and iterate based on feedback to develop a wireframe prototype.

4. Success or completion criteria. Please describe in detail.

    Success

5.  Allocated time

    5 days

6.  Start date and end date of the issue/task

    20/11/2023-25/11/2023

7. What is the priority of the task

    High

Issue/Task Comments Template 
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by 2101309** [comment]
reviewed

**Comment by Jr-Goh** [comment]
Reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by brandonbljl** [comment]
Describe the work done in detail.
- Created a detailed wireframe prototype

Has this work been committed to the repo?
- Yes

How does the work affect success or completion criteria?
- Work was completed within the designated timeframe, meeting task requirements.

Start date and end date of the work done
- Start date: 20/11/2023 End date: 25/11/2023

**Comment by KotoneZQ** [comment]
reviewed

**Comment by brandonbljl** [comment]
closed - 26/11
