### ISSUE TITLE
3.3 Black Box Testing

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#46]
> 1. Task title ID: #46
2. What is the task about?

> To create a black box testing on one of the use cases created based on the project requirement

3. What are the goals of the task?

> To successfully create and do a black box testing on the chosen use case with test cases provided

4. Success or completion criteria.

> Complete Task #47 

> Successfully create a test case for the use case

5. Allocated time

> 2 Days

6. Start date and end date of the issue/task

> 18 - 20 Nov 2023

7. What is the priority of the task

> High Priority

**Comment by KotoneZQ** [comment]
18 Nov 2023

Helps with the Black Box testing

> Create a decision table

> Create test cases for Use case

**Comment by 2101309** [comment]
reviewed.

**Comment by Jr-Goh** [comment]
Assisted in the Black Box testing component

**Comment by KotoneZQ** [comment]
reviewed.

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed
