### ISSUE TITLE
3.3.1 Create a Decision Table

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#47]
1. Task title ID: #47
2. What is the task about?

> To create a decision table for black box testing.

3. What are the goals of the task?

> Identify the causes and effects of the chosen use case,

> Calculate the possible combination for black box test cases

4. Success or completion criteria.

> Choose a use case for BB testing

> Identify all the causes and effects

> Create & complete test cases

5. Allocated time

> 2 Days

6. Start date and end date of the issue/task

> 18 - 20 Nov 2023

7. What is the priority of the task

> Medium

**Comment by KotoneZQ** [comment]
18 Nov 2023
Create a decision table for Black box testing

> Choose a Use case (Login)

> Identify the causes & effects

> Create test cases for Use case

**Comment by 2101309** [comment]
reviewed

**Comment by Jr-Goh** [comment]
Reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by KotoneZQ** [comment]
closed (26/11)
