### ISSUE TITLE
3.4 White Box Testing

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#48]
1. Task title ID: #48
2. What is the task about? Please describe in detail.
Is a software testing method that examines the internal structure and logic of a software application
3. What are the goals of the task? Please describe in detail.
The goal is to ensure that all lines of code, paths, and branches within the software are tested
4. Success or completion criteria. Please describe in detail.
The success criteria collectively ensure that the white-box testing process is thorough, effective, and contributes to the overall quality and reliability of the software.
5. Allocated time
7 days
6. Start date and end date of the issue/task
18/11/2023 - 25/11/2023
8. What is the priority of the task
High 

Issue/Task Comments Template 
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by 2101309** [comment]
pseudocode for whitebox testing done.
CFG diagram review needed.
Cyclomatic Complexity review needed.
Basis Path Testing review needed.
Test case ongoing.

**Comment by KotoneZQ** [comment]
help with pseudocode, CFG diagram, Basis Path testing

reviewed

**Comment by 2101309** [comment]
Test Case done using branch coverage review needed.

**Comment by KotoneZQ** [comment]
add CFG diagram for basis path testing

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
Reviewed

**Comment by Kai-i-i-i** [comment]
Helped to make the pseudo code, reviewed overall

**Comment by gitdanzel** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by 2101309** [comment]
Closed(26/11)
