### ISSUE TITLE
3.4.1 Create a Control Flow Graph

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#49]
1. Task title ID: #49
2. What is the task about? Please describe in detail.
To draw a visual representation of a system's series of steps, processes, or operations.
3. What are the goals of the task? Please describe in detail.
The diagrams can be a valuable aid in performing white-box testing as they represent the paths that can be taken through a program during its execution.
4. Success or completion criteria. Please describe in detail.
The success conditions for using CFG diagrams in white-box testing involve achieving comprehensive code coverage
5. Allocated time
5 days
6. Start date and end date of the issue/task
20/11/2023-25/11/2023
7. What is the priority of the task
High Priority

Issue/Task Comments Template 
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
5. Start date and end date of the work done

**Comment by KotoneZQ** [comment]
help with the creation of control flow graph
reviewed

**Comment by 2101309** [comment]
control flow graph done. review needed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
Reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by 2101309** [comment]
Closed(26/11)
