### ISSUE TITLE
1.6.2 List out the Functional Requirements + 1.6.4 List out the Non-Functional Requirements

### ISSUE THREAD

**Issue by Kai-i-i-i** [KotoneZQ/INF2001_P7-6_Project#5]
1. Task title ID: #05
2. What is the task about? Turn result of meeting to FR & NFR
3. What are the goals of the task? Please describe in detail.
To clearly lay out the different functional and non-functional requirements that we will be following to construct our system, and the functions that it will be able to perform. This is the continuation of the product functionality section, and we will be going more in-depth into the functions in this section.
4. Success or completion criteria. Please describe in detail.
Write an insightful, in-depth description of the functionalities that were detailed in the product functionality section.
5. Allocated time
6 days
6. Start date and end date of the issue/task
13/9/2023 to 17/9/2023 (FR)
16/9/2023 to 19/9/2023 (NFR)
7. What is the priority of this task?
High

Issue/Task Comments Template
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by Jr-Goh** [comment]
Reviewed

**Comment by 2101309** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
Vetted requirements 16/9

**Comment by KotoneZQ** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by gitdanzel** [comment]
update 18/9 added in-depth descriptions of functional requirements and non-functional requirements

**Comment by gitdanzel** [comment]
Issue/Task Comments Template

Describe the work done in detail.
Provided a more in-depth description of the functional and non-functional requirements, clearly detailing the interactions between user and system.
Has this work been committed to the repo?
Yes
How does the work affect success or completion criteria?
It adheres to both the success and completion criteria.
Start date and end date of the work done
13/9/2023 to 19/9/2023
