### ISSUE TITLE
3.5 Video Making of Final Prototype

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#50]
1. Task title ID: #50
2. What is the task about? Please describe in detail.
Make a video demo within 5minute with a narration of the prototype. 
3. What are the goals of the task? Please describe in detail.
To help users understand the software better and the different requirements and use cases.
4. Success or completion criteria. Please describe in detail.
The video is within 5 minutes and all use cases and requirements are covered.

5. Allocated time
1 day
6. Start date and end date of the issue/task
25/11/2023 - 25/11/2023
7. What is the priority of the task
Medium

**Comment by 2101309** [comment]
Done with the 2nd half of the video.  review needed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
Reviewed

**Comment by Kai-i-i-i** [comment]
presented first half of prototype in video, combined the 2 parts

**Comment by KotoneZQ** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by 2101309** [comment]
Closed (26/11)
