### ISSUE TITLE
1.4.1 Figure out what the Product scope

### ISSUE THREAD

**Issue by Kai-i-i-i** [KotoneZQ/INF2001_P7-6_Project#6]
1. Task title ID: #06
2. What is the task about?

> Providing a short description of the software scope, boundaries, and its purpose, including relevant benefits, objectives, and goals.

3. What are the goals of the task?

> To allow all readers of our document to get a brief idea of our product, specifically the scope, benefits, and goals of the product.

4. Success or completion criteria.

> To successfully provide a description of the software/product.

5. Allocated time

> 2 Days

16. Start date and end date of the issue/task

> 11/9 - 13/9

7. What is the priority of the task

> High priority

Issue/Task Comments Template
1. Describe the work done in detail.
2. Has this work been committed to the repo?
3. How does the work affect success or completion criteria?
4. Start date and end date of the work done

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by KotoneZQ** [comment]
1. Discuss about what is required to be in the report writing

> - Identify each requirement as functional/non-functional
> - Allocate sub-issue #8 and #9 among members
> - Draw a System Architecture Diagram

2. Questions to prepare for clarification with the professor during the next lesson

**Comment by Jr-Goh** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
Added a short description, the scope boundaries, purpose and benefits and objectives and goals to the document. Pending review from rest of the team.

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
Closed - 22-9
