### ISSUE TITLE
1.7.2 Create a Project Management Plan

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#7]
Follow the template in the slides (read ahead week 3 lecture materials).

Task title ID: M1.4.2 Project Management #7
What is the task about?

> Create a Gantt chart with the provided details for our project schedule

What are the goals of the task?

> To provide a schedule of what we have planned to do in estimation as well as keeping track of each member's tasks
> To assign each task to members with indicated start and due date

Success or completion criteria.

> Finish the Gantt chart with a detailed and estimated schedule

Allocated time

> 2 Days

Start date and end date of the issue/task

> 19 Sept - 21 Sept

What is the priority of the task

> High priority

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by KotoneZQ** [comment]
Created a Gantt chart in Google Drive
Fill in the required tasks and summary for each Milestone of the project
Indicate task owner, start date and end date, and percentage of task complete for currently and completed tasks

**Comment by KotoneZQ** [comment]
17 Sept 2023, 8pm - 12am

Discussed Gantt chart among group
Modified and fill up the remaining tasks for each Milestone of the project

**Comment by KotoneZQ** [comment]
Pending reviewed from team members

**Comment by Jr-Goh** [comment]
reviewed

**Comment by brandonbljl** [comment]
reviewed

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by KotoneZQ** [comment]
closed (22/9)
