### ISSUE TITLE
1.4.2 Research on Background literature

### ISSUE THREAD

**Issue by KotoneZQ** [KotoneZQ/INF2001_P7-6_Project#9]
1. Task title ID: #9
2. perform background research on the topic domain and include findings in our background literature.
3. The goal of this is to gain understanding on our domain and why we are doing this topic.
4. Successfully look for research material and show that there is a purpose doing our topic.
5. 2 days
6. 11/09/23 - 13/09/23

**Comment by Kai-i-i-i** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by Jr-Goh** [comment]
Done some topic background research and included findings in background literature. 11/09/23 - 13/09/23

**Comment by brandonbljl** [comment]
reviewed

**Comment by gitdanzel** [comment]
reviewed

**Comment by KotoneZQ** [comment]
reviewed

**Comment by 2101309** [comment]
reviewed
